- name: Downloads Bitwarden CLI
  become: true
  ansible.builtin.uri:
    url: https://vault.bitwarden.com/download/?app=cli&platform=linux
    ca_path: "{{  zscalercert }}" 
    follow_redirects: safe
    status_code:
      - 200
      - 304 # Not modified
    force: yes
    dest: /tmp/bw.zip
- name: Unzips Bitwarden package
  become: true
  ansible.builtin.unarchive:
    src: /tmp/bw.zip
    dest: /usr/bin/
    mode: '755'
- name: Set environment variable to validate Zscaler certificate - CONF
  vars:
    current_user: "{{ lookup('env', 'USER')}}"
  ansible.builtin.lineinfile:
    path: "/home/{{ current_user }}/bw_cli_cert.conf"
    state: present
    create: yes
    line: "export NODE_EXTRA_CA_CERTS={{ zscalercert }}"
- name: Set environment variable to validate Zscaler certificate - PROFILE
  vars:
    current_user: "{{ lookup('env', 'USER')}}"
  ansible.builtin.lineinfile:
    path: "/home/{{ current_user }}/.profile"
    state: present
    line: "source /home/{{ current_user }}/bw_cli_cert.conf"
