- name: Create ~/Documents/repos folder
  ansible.builtin.file:
    path: /home/{{ usuario }}/Documents/repos
    state: directory
    mode: '0755'
    
- name: Create link from ~/repos to ~/Documents/repos
  ansible.builtin.file:
    src: /home/{{ usuario }}/Documents/repos
    dest: /home/{{ usuario }}/repos
    state: link
